config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    
    get 'company_turns_week_schedule', as: 'company_schedule'
    get 'company_engineer_turn_availabilities', as: 'edit_turn_availabilities'
    post 'update_company_engineer_turn_availabilities', as: 'update_turn_availabilities'
    
  end

  resources :engineers

  root 'engineers#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/turn_availability.rb
class TurnAvailability < ApplicationRecord
  belongs_to :engineer
  belongs_to :company
  belongs_to :turn
end

app/controllers/turn_availabilities_controller.rb
class TurnAvailabilitiesController < ApplicationController
  before_action :set_turn_availability, only: %i[ show edit update destroy ]

  # GET /turn_availabilities or /turn_availabilities.json
  def index
    @turn_availabilities = TurnAvailability.all
  end

  # GET /turn_availabilities/1 or /turn_availabilities/1.json
  def show
  end

  # GET /turn_availabilities/new
  def new
    @turn_availability = TurnAvailability.new
  end

  # GET /turn_availabilities/1/edit
  def edit
  end

  # POST /turn_availabilities or /turn_availabilities.json
  def create
    @turn_availability = TurnAvailability.new(turn_availability_params)

    respond_to do |format|
      if @turn_availability.save
        format.html { redirect_to turn_availability_url(@turn_availability), notice: "Turn availability was successfully created." }
        format.json { render :show, status: :created, location: @turn_availability }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @turn_availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turn_availabilities/1 or /turn_availabilities/1.json
  def update
    respond_to do |format|
      if @turn_availability.update(turn_availability_params)
        format.html { redirect_to turn_availability_url(@turn_availability), notice: "Turn availability was successfully updated." }
        format.json { render :show, status: :ok, location: @turn_availability }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @turn_availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turn_availabilities/1 or /turn_availabilities/1.json
  def destroy
    @turn_availability.destroy

    respond_to do |format|
      format.html { redirect_to turn_availabilities_url, notice: "Turn availability was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turn_availability
      @turn_availability = TurnAvailability.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turn_availability_params
      params.require(:turn_availability).permit(:date, :engineer_id, :company_id, :turn_id)
    end
end

app/helpers/turn_availabilities_helper.rb
module TurnAvailabilitiesHelper
end

app/views/turn_availabilities/_form.html.erb
<%= form_with(model: turn_availability, class: "contents") do |form| %>
  <% if turn_availability.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(turn_availability.errors.count, "error") %> prohibited this turn_availability from being saved:</h2>

      <ul>
        <% turn_availability.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :date %>
    <%= form.datetime_field :date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :engineer_id %>
    <%= form.text_field :engineer_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :company_id %>
    <%= form.text_field :company_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :turn_id %>
    <%= form.text_field :turn_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/turn_availabilities/_turn_availability.html.erb
<div id="<%= dom_id turn_availability %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Date:</strong>
    <%= turn_availability.date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Engineer:</strong>
    <%= turn_availability.engineer_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Company:</strong>
    <%= turn_availability.company_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Turn:</strong>
    <%= turn_availability.turn_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this turn availability", turn_availability, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this turn availability', edit_turn_availability_path(turn_availability), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/turn_availabilities/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing turn availability</h1>

  <%= render "form", turn_availability: @turn_availability %>

  <%= link_to "Show this turn availability", @turn_availability, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to turn availabilities", turn_availabilities_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/turn_availabilities/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Turn availabilities</h1>
    <%= link_to 'New turn availability', new_turn_availability_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="turn_availabilities" class="min-w-full">
    <%= render @turn_availabilities %>
  </div>
</div>

app/views/turn_availabilities/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New turn availability</h1>

  <%= render "form", turn_availability: @turn_availability %>

  <%= link_to 'Back to turn availabilities', turn_availabilities_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/turn_availabilities/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @turn_availability %>

    <%= link_to 'Edit this turn_availability', edit_turn_availability_path(@turn_availability), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this turn_availability', turn_availability_path(@turn_availability), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to turn_availabilities', turn_availabilities_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>