config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    
    get 'company_turns_week_schedule', as: 'company_schedule'
    get 'company_engineer_turn_availabilities', as: 'edit_turn_availabilities'
    post 'update_company_engineer_turn_availabilities', as: 'update_turn_availabilities'
    
  end

  resources :engineers

  root 'engineers#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/company.rb
class Company < ApplicationRecord
    has_many :turns,  dependent: :destroy
    has_many :turn_availabilities,  dependent: :destroy

    has_and_belongs_to_many :engineers

    accepts_nested_attributes_for :turn_availabilities



    store_accessor :schedule, 
                    :monday, 
                    :tuesday, 
                    :wednesday, 
                    :thursday, 
                    :friday, 
                    :saturday, 
                    :sunday


    def create_turns(date)
        days = date.all_week
        days.each do |day|
            week_day_start_time = self.schedule[day.strftime("%A").downcase]
            duration = ((Time.parse('24:00')-Time.parse(week_day_start_time ))/3600).to_i
            duration.times do |i|
                Turn.create(date: day.to_datetime + (Time.parse(week_day_start_time )+(i*3600)).seconds_since_midnight.seconds, company_id: self.id)
                #create turn availabilities for each engineer in the company
            end 
        end
        self.engineers.each do |engineer|
            engineer.create_turns_availabilities(date, self)
        end
    end

    def count_turns_per_engineer(date)
        turns_per_engineer = {}
        self.engineers.each do |engineer|
            turns_per_engineer[engineer.name] = engineer.turns.where(company: self, date: date.beginning_of_week..date.end_of_week.at_end_of_day).count
        end
        turns_per_engineer
    end

    def count_available_turns_per_engineer(date)
        turns_per_engineer = {}
        self.engineers.each do |engineer|
            turns_per_engineer[engineer.name] = engineer.available_turns(date, self).count
        end
        turns_per_engineer
    end


    def assign_best_turns(date)
        self.turns.where(date: date.beginning_of_week..date.end_of_week.at_end_of_day).update_all(engineer_id: nil)
        turns_per_engineer = self.count_available_turns_per_engineer(date)
        turns_per_engineer = turns_per_engineer.sort_by {|k,v| v}.to_h
        turns_per_engineer.each do |engineer, turns|
            engineer = Engineer.find_by(name: engineer)
            engineer.available_turns(date, self).each do |available_turn|
                if available_turn.turn.engineer.nil?
                    available_turn.turn.update(engineer_id: engineer.id)
                end
            end
        end
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies or /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save

        @company.create_turns(Date.today)

        format.html { redirect_to company_url(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    puts(params)
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def company_turns_week_schedule
    @turns_hours = {"00:00-01:00" => 0, "01:00-02:00" => 1, "02:00-03:00" => 2, "03:00-04:00" => 3, "04:00-05:00" => 4, "05:00-06:00" => 5, "06:00-07:00" => 6, "07:00-08:00" => 7, "08:00-09:00" => 8, "09:00-10:00" => 9, "10:00-11:00" => 10, "11:00-12:00" => 11, "12:00-13:00" => 12, "13:00-14:00" => 13, "14:00-15:00" => 14, "15:00-16:00" => 15, "16:00-17:00" => 16, "17:00-18:00" => 17, "18:00-19:00" => 18, "19:00-20:00" => 19, "20:00-21:00" => 20, "21:00-22:00" => 21, "22:00-23:00" => 22, "23:00-00:00" => 23}
    @date = params[:date] ? Date.parse(params[:date]).at_beginning_of_week : Date.today.at_beginning_of_week
    @days = @date.beginning_of_week..@date.end_of_week
    @company = Company.find(params[:company_id])
    @weeks = (Date.today - @company.created_at.to_date).to_i / 7
    @weeks = @weeks <= 5 ? @weeks : 5
    
    @turns = @company.turns.where(date: @date.beginning_of_week..@date.end_of_week.at_end_of_day)

    if @turns.empty?
      @company.create_turns(@date)
      @turns = @company.turns.where(date: @date.beginning_of_week..@date.end_of_week.at_end_of_day)
    end

    @count_turns_per_engineer = @company.count_turns_per_engineer(@date)
    
  end

  def company_engineer_turn_availabilities
    @turns_hours = {"00:00-01:00" => 0, "01:00-02:00" => 1, "02:00-03:00" => 2, "03:00-04:00" => 3, "04:00-05:00" => 4, "05:00-06:00" => 5, "06:00-07:00" => 6, "07:00-08:00" => 7, "08:00-09:00" => 8, "09:00-10:00" => 9, "10:00-11:00" => 10, "11:00-12:00" => 11, "12:00-13:00" => 12, "13:00-14:00" => 13, "14:00-15:00" => 14, "15:00-16:00" => 15, "16:00-17:00" => 16, "17:00-18:00" => 17, "18:00-19:00" => 18, "19:00-20:00" => 19, "20:00-21:00" => 20, "21:00-22:00" => 21, "22:00-23:00" => 22, "23:00-00:00" => 23}
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @company = Company.find(params[:company_id])
    @engineer = Engineer.find(params[:engineer_id])
    @days = @date.beginning_of_week..@date.end_of_week
    @company_engineers = @company.engineers

    @turns = @company.turns.where(date: @date.beginning_of_week..@date.end_of_week.at_end_of_day)
    @engineer_turn_availabilities = @engineer.turn_availabilities.where(turn_id: @turns.ids, company_id: @company.id)
  end

  def update_company_engineer_turn_availabilities
    @company = Company.find(params[:company_id])
    @engineer = Engineer.find(params[:engineer_id])
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @days = @date.beginning_of_week..@date.end_of_week
    @company_engineers = @company.engineers

    @turns = @company.turns.where(date: @date.beginning_of_week..@date.end_of_week.at_end_of_day)
    @engineer_turn_availabilities = @engineer.turn_availabilities.where(turn_id: @turns.ids, company_id: @company.id)

    @engineer_turn_availabilities.each do |engineer_turn_availability|
      if params[:turn_availability_ids].include?(engineer_turn_availability.id.to_s)
        engineer_turn_availability.update(available: true)
      else
        engineer_turn_availability.update(available: false)
      end
    end

    @company.assign_best_turns(@date)

    redirect_to company_company_schedule_url(@company, @engineer, date: @date)
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :schedule,:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday, :engineer_ids => [], :turn_availability => [])
    end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_assigned_engineer.html.erb
 <td class="border px-4 py-2 <%= engineer.color %>-bg-color" ><%= engineer.name %></td>

app/views/companies/_company.html.erb
<div id="<%= dom_id company %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= company.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Schedule:</strong>
    <%= company.schedule %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this company", company, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this company', edit_company_path(company), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/companies/_form.html.erb
<%= form_with(model: company, class: "contents") do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5 w-1/3">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5 w-1/3">
    <%= form.collection_check_boxes :engineer_ids, Engineer.all, :id, :name, include_hidden: false do |b| %>
      <%= b.check_box %> <%= b.label %>
    <% end %>
  </div>

  <div class="my-5">
    <label for="schedule[:monday]" class="mb-2 text-sm font-medium text-gray-900 ">Lunes</label>
    <%= form.time_field :monday, class:'mr-2' %>
    <label for="schedule[:tuesday]" class="mb-2 text-sm font-medium text-gray-900 ">Martes</label>
    <%= form.time_field :tuesday, class:'mr-2'  %>
    <label for="schedule[:wednesday]" class="mb-2 text-sm font-medium text-gray-900 ">Miercoles</label>
    <%= form.time_field :wednesday, class:'mr-2'  %>
    <label for="schedule[:thursday]" class="mb-2 text-sm font-medium text-gray-900 ">Jueves</label>
    <%= form.time_field :thursday, class:'mr-2'  %>
    <label for="schedule[:friday]" class="mb-2 text-sm font-medium text-gray-900 ">Viernes</label>
    <%= form.time_field :friday, class:'mr-2'  %>
    <label for="schedule[:saturday]" class="mb-2 text-sm font-medium text-gray-900 ">Sabado</label>
    <%= form.time_field :saturday, class:'mr-2'  %>
    <label for="schedule[:sunday]" class="mb-2 text-sm font-medium text-gray-900 ">Domingo</label>
    <%= form.time_field :sunday %>
  </div>



  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/companies/_week_selector.html.erb
<select class="form-select appearance-none
            block
            w-full
            px-3
            py-1.5
            text-base
            font-normal
            text-gray-700
            bg-white bg-clip-padding bg-no-repeat
            border border-solid border-gray-300
            rounded
            transition
            ease-in-out
            m-0
            focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" id="company-selector" onchange="redirect_to_engineer_turns(<%= company_id %> ,this.value)">
    
    <% if weeks > 0 %>
        <% (weeks).downto(1).each do |i| %>
            <% select_date = i.week.ago.at_beginning_of_week.to_date %>
            
            <% if  date == select_date %>
                <option value="<%= select_date %>" selected>Semana <%= select_date.strftime("%W")%> del <%= select_date.strftime("%Y")%></option>
            <% else %>
                <option value="<%= select_date %>" >Semana <%= select_date.strftime("%W")%> del <%= select_date.strftime("%Y")%></option>
            <% end %>
        <% end %>
    <% end %>

    <% if date == Date.today.at_beginning_of_week.to_date %>
        <option value="<%= Date.today.at_beginning_of_week.to_date %>" selected>Semana <%= Date.today.at_beginning_of_week.strftime("%W")%> del <%= Date.today.at_beginning_of_week.strftime("%Y")%></option>
    <% else %>
        <option value="<%= Date.today.at_beginning_of_week.to_date %>" >Semana <%= Date.today.at_beginning_of_week.strftime("%W")%> del <%= Date.today.at_beginning_of_week.strftime("%Y")%></option>
    <% end %>
    
    <% 5.times do |i| %>
        <% select_date = (i+1).week.from_now.at_beginning_of_week.to_date %>
        <% if  date == select_date %>
            <option value="<%= select_date %>" selected>Semana <%= select_date.strftime("%W")%> del <%= select_date.strftime("%Y")%></option>
        <% else %>
            <option value="<%= select_date %>" >Semana <%= select_date.strftime("%W")%> del <%= select_date.strftime("%Y")%></option>
        <% end %>
    <% end %>
</select>

<script>
    function redirect_to_engineer_turns(company_id, date) {
        window.location.href = "/companies/" + company_id + "/company_turns_week_schedule?date=" + date;
    }
</script>

app/views/companies/company_engineer_turn_availabilities.html.erb
<%= form_with(url: company_update_turn_availabilities_url(company_id: @company.id, engineer_id: @engineer) , method: :post, local: true) do |form| %>
    <%= form.hidden_field :date, value: @date %>
    
    <div class="grid grid-rows-8 grid-cols-6 gap-4">
        <div class="col-span-4 col-start-2">
            <h4 class="text-center mb-4 text-2xl font-extrabold tracking-tight leading-none text-gray-900 md:text-3xl lg:text-4xl ">Disponibilidad de <%= @engineer.name %></h4>
        </div>
        <div class="row-start-2">
            <%= form.submit "Editar disponibilidad", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
        </div>
        <div class="row-start-2 col-start-1 col-span-1" >
        
            
            <select class="form-select appearance-none
            block
            w-full
            px-3
            py-1.5
            text-base
            font-normal
            text-gray-700
            bg-white bg-clip-padding bg-no-repeat
            border border-solid border-gray-300
            rounded
            transition
            ease-in-out
            m-0
            focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" id="company-selector" onchange="redirect_to_engineer_turns(<%= @company.id %> ,this.value)">
                <% @company_engineers.each do |e| %>
                    <% if e.id == @engineer.id %>
                        <option value="<%= e.id %>" selected><%= e.name %></option>
                    <% else %>
                        <option value="<%= e.id %>"><%= e.name %></option>
                    <% end %>
                <% end %>
            </select>
            
        </div>
        <div class='row-start-2 row-span-6 col-start-2 col-span-4'>
            <table class="table-auto">
                <thead>
                    <tr>
                        <th class="border px-4 py-2">Horario</th>
                        <th class="border px-4 py-2">Lunes</th>
                        <th class="border px-4 py-2">Martes</th>
                        <th class="border px-4 py-2">Miércoles</th>
                        <th class="border px-4 py-2">Jueves</th>
                        <th class="border px-4 py-2">Viernes</th>
                        <th class="border px-4 py-2">Sábado</th>
                        <th class="border px-4 py-2">Domingo</th>
                        
                    </tr>
                </thead>
                <tbody>
                    <% @turns_hours.each do |time_range, start_hour|%>
                        <tr>
                            <td class="border px-4 py-2"><%= time_range %></td>
                            <% @days.each do |day| %>
                                <% engineer_turn_availability = @engineer_turn_availabilities.where(date: day.to_datetime + start_hour.hours).first %>
                                <% if engineer_turn_availability.present?%>
                                    <td class="border px-4 py-2">
                                        <%= form.check_box :turn_availability_ids, {multiple: true, checked: engineer_turn_availability.available?}, engineer_turn_availability.id, nil %>
                                    </td>
                                <% else %>
                                    <td class="border px-4 py-2"></td>
                                <% end %>
                            
                            <% end %>
                        </tr>
                    <% end %>
                </tbody>
            </table>
                
        </div>
    </div>
<% end %>

<script>
    function redirect_to_engineer_turns(company_id, engineer_id) {
        window.location.href = "/companies/" + company_id + "/company_engineer_turn_availabilities?date=" + "<%= @date %>" + "&engineer_id=" + engineer_id;
    }
</script>

app/views/companies/company_turns_week_schedule.html.erb
<div class="grid grid-rows-8 grid-cols-3 gap-4">    
    <div class="col-span-1 col-start-2">
        <h4 class="mb-4 text-2xl font-extrabold tracking-tight leading-none text-gray-900 md:text-3xl lg:text-4xl">Turnos Asignados</h4>
    </div>
    <div class="col-span-1 col-start-3">
        <% if !@company.engineers.empty? %>
            <%= link_to 'Editar Disponibilidad', company_edit_turn_availabilities_path(@company, engineer_id: @company.engineers.first, date: @date),  class: "mt-2 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium"%>
        <% end %>
    </div>
    <div class="row-start-2 col-start-1 col-span-1" >
        <div class="mb-3 xl:w-96"> 
            <select class="form-select appearance-none
            block
            w-full
            px-3
            py-1.5
            text-base
            font-normal
            text-gray-700
            bg-white bg-clip-padding bg-no-repeat
            border border-solid border-gray-300
            rounded
            transition
            ease-in-out
            m-0
            focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" id="company-selector" onchange="redirect_to_company(this.value)">
                <% Company.all.each do |c| %>
                    <% if c.id == @company.id %>
                        <option value="<%= c.id %>" selected><%= c.name %></option>
                    <% else %>
                        <option value="<%= c.id %>"><%= c.name %></option>
                    <% end %>
                <% end %>
            </select>
        </div>

        <%= render partial: 'week_selector', locals: {company_id: @company.id, weeks: @weeks, date: @date} %>

        <p class="ml-1 mt-3 mb-4 text-3lg font-extrabold text-gray-900 md:text-2lg lg:text-3lg">Del <%= @days.first.strftime('%m/%d/%Y') %> al <%= @days.last.strftime('%m/%d/%Y') %></p>

        
    </div>
    <div class='row-start-3 col-start-1 col-span-1'>
        <table class="table-auto">
            <thead></thead>
            <tbody>
                <% @count_turns_per_engineer.each do |name, count| %>
                    <tr>
                        <td class="border px-4 py-2"><%= name %></td>
                        <td class="border px-4 py-2"><%= count %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>

    <div class='row-start-2 row-span-6 col-start-2 col-span-2'>
        <table class="table-auto">
            <thead>
                <tr>
                    <th class="border px-4 py-2">Horario</th>
                    <th class="border px-4 py-2">Lunes</th>
                    <th class="border px-4 py-2">Martes</th>
                    <th class="border px-4 py-2">Miércoles</th>
                    <th class="border px-4 py-2">Jueves</th>
                    <th class="border px-4 py-2">Viernes</th>
                    <th class="border px-4 py-2">Sábado</th>
                    <th class="border px-4 py-2">Domingo</th>
                </tr>
            </thead>
            <tbody>
                <% @turns_hours.each do |time_range, start_hour|%>
                    <tr>
                        <td class="border px-4 py-2 bg-green-600"><%= time_range %></td>
                        <% @days.each do |day| %>
                            <% turn = @turns.where(date: day.to_datetime + start_hour.hours).first %>
                            <% if turn.present? %>
                                <% if turn.engineer.present? %>
                                    <td class="border px-4 py-2 bg-green-300 text-center" ><%= turn.engineer.name %></td>
                                <% else %>
                                    <td class="border px-4 py-2 text-center"><i class="fa-solid fa-triangle-exclamation text-yellow-600"></i></td>
                                <% end %>
                            <% else %>
                                <td class="px-4 py-2 bg-gray-200"></td>
                            <% end %>
                            </td>
                        <% end %>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

<script>
    function redirect_to_company(company_id) {
        window.location.href = "/companies/" + company_id + "/company_turns_week_schedule";
    }
</script>

app/views/companies/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing company</h1>

  <%= render "form", company: @company %>

  <%= link_to "Show this company", @company, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to companies", companies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/companies/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Companies</h1>
    <%= link_to 'New company', new_company_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="companies" class="min-w-full">
    <%= render @companies %>
  </div>
</div>

app/views/companies/new.html.erb
<div class="mx-auto w-full">
  <h1 class="font-bold text-4xl">New company</h1>

  <%= render "form", company: @company %>

  <%= link_to 'Back to companies', companies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/companies/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @company %>

    <%= link_to 'Company Schedule', company_company_schedule_path(@company, date: Date.today),  class: "mt-2 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium"%>

    <%= link_to 'Edit this company', edit_company_path(@company), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this company', company_path(@company), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to companies', companies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>