config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    
    get 'company_turns_week_schedule', as: 'company_schedule'
    get 'company_engineer_turn_availabilities', as: 'edit_turn_availabilities'
    post 'update_company_engineer_turn_availabilities', as: 'update_turn_availabilities'
    
  end

  resources :engineers

  root 'engineers#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/engineer.rb
class Engineer < ApplicationRecord
    has_many :turns 
    has_many :turn_availabilities,  dependent: :delete_all

    has_and_belongs_to_many :companies

    def create_turns_availabilities(date, company)
        company_turns = company.turns.where(date: date.beginning_of_week..date.end_of_week.at_end_of_day)
        
        company_turns.each do |turn|
            TurnAvailability.create(turn_id: turn.id, engineer_id: self.id, company_id: company.id, available: false, date: turn.date)
        end
    end

    def available_turns(date, company)
        self.turn_availabilities.where(company: company, date: date.beginning_of_week..date.end_of_week.at_end_of_day, available: true)
    end

    def unavailable_turns(date, company)
        self.turn_availabilities.where(company: company, date: date.beginning_of_week..date.end_of_week.at_end_of_day, available: false)
    end
end

app/controllers/engineers_controller.rb
class EngineersController < ApplicationController
  before_action :set_engineer, only: %i[ show edit update destroy ]

  # GET /engineers or /engineers.json
  def index
    @engineers = Engineer.all
  end

  # GET /engineers/1 or /engineers/1.json
  def show
  end

  # GET /engineers/new
  def new
    @engineer = Engineer.new
  end

  # GET /engineers/1/edit
  def edit
  end

  # POST /engineers or /engineers.json
  def create
    @engineer = Engineer.new(engineer_params)

    respond_to do |format|
      if @engineer.save
        format.html { redirect_to engineer_url(@engineer), notice: "Engineer was successfully created." }
        format.json { render :show, status: :created, location: @engineer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @engineer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engineers/1 or /engineers/1.json
  def update
    respond_to do |format|
      if @engineer.update(engineer_params)
        format.html { redirect_to engineer_url(@engineer), notice: "Engineer was successfully updated." }
        format.json { render :show, status: :ok, location: @engineer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @engineer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engineers/1 or /engineers/1.json
  def destroy
    @engineer.destroy

    respond_to do |format|
      format.html { redirect_to engineers_url, notice: "Engineer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engineer
      @engineer = Engineer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def engineer_params
      params.require(:engineer).permit(:name, :color)
    end
end

app/helpers/engineers_helper.rb
module EngineersHelper
end

app/views/engineers/_engineer.html.erb
<div id="<%= dom_id engineer %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= engineer.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Color:</strong>
    <%= engineer.color %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this engineer", engineer, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this engineer', edit_engineer_path(engineer), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/engineers/_form.html.erb
<%= form_with(model: engineer, class: "contents") do |form| %>
  <% if engineer.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(engineer.errors.count, "error") %> prohibited this engineer from being saved:</h2>

      <ul>
        <% engineer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :color %>
    <%= form.text_field :color, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/engineers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing engineer</h1>

  <%= render "form", engineer: @engineer %>

  <%= link_to "Show this engineer", @engineer, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to engineers", engineers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/engineers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Engineers</h1>
    <%= link_to 'New engineer', new_engineer_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="engineers" class="min-w-full">
    <%= render @engineers %>
  </div>
</div>

app/views/engineers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New engineer</h1>

  <%= render "form", engineer: @engineer %>

  <%= link_to 'Back to engineers', engineers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/engineers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @engineer %>

    <%= link_to 'Edit this engineer', edit_engineer_path(@engineer), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this engineer', engineer_path(@engineer), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to engineers', engineers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>